#Yaml routing example
homepage:
    path:     /
    defaults: { _controller: BecekEstatehunterBundle:Default:index }
    methods:  ['GET','POST']
    requirements:
            page: '\d+'

gratka:
    path:     /gratka/{page}
    defaults: { _controller: BecekEstatehunterBundle:Default:gratka, page: 1 }
    methods:  ['GET','POST']
    requirements:
            page: '\d+'

otodom:
    path:     /otodom/{page}
    defaults: { _controller: BecekEstatehunterBundle:Default:otodom, page: 1 }
    methods:  ['GET','POST']
    requirements:
            page: '\d+'

output:
    path:     /output
    defaults: { _controller: BecekEstatehunterBundle:Default:getOutput }
    methods:  ['GET','POST']

becek_estatehunter:
    resource: "@BecekEstatehunterBundle/Controller/"
    type:     annotation
    prefix:   /


