#Yaml routing example
homepage:
    path:     /
    defaults: { _controller: BecekEstatehunterBundle:Default:index }
    methods:  ['GET','POST']
    requirements:
            page: '\d+'

gratka:
    path:     /gratka/{page}
    defaults: { _controller: BecekEstatehunterBundle:Default:gratka, page: 1 }
    methods:  ['GET','POST']
    requirements:
            page: '\d+'

otodom:
    path:     /otodom
    defaults: { _controller: BecekEstatehunterBundle:Default:otodom }
    methods:  ['GET','POST']

localization:
    path:     /localization
    defaults: { _controller: BecekEstatehunterBundle:Default:localization }
    methods:  ['POST']

olx:
    path:     /olx
    defaults: { _controller: BecekEstatehunterBundle:Default:olx }
    methods:  ['GET','POST']

output:
    path:     /output
    defaults: { _controller: BecekEstatehunterBundle:Default:getOutput }
    methods:  ['GET','POST']

becek_estatehunter:
    resource: "@BecekEstatehunterBundle/Controller/"
    type:     annotation
    prefix:   /


