<?php
/**
 * Created by PhpStorm.
 * User: micha
 * Date: 23.05.2018
 * Time: 19:17
 */

namespace Becek\EstatehunterBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FlatFilterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options) {

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

}