<?php

namespace Becek\EstatehunterBundle\Repository\Filters;

/**
 * FlatFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatFilterRepository extends \Doctrine\ORM\EntityRepository
{
}
