<?php

namespace Becek\EstatehunterBundle\Repository\Filters;

/**
 * FlatFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatFilterRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $limit
     * @return array
     */
    public function findOrderedByDateLastSearchWithLimit($limit)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM BecekEstatehunterBundle:Filters\FlatFilter f ORDER BY f.dateLastSearch')
            ->setMaxResults($limit)
            ->getResult();
    }

    /**
     * @return array
     */
    public function getFlatFilterCount()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(f) FROM BecekEstatehunterBundle:Filters\FlatFilter f')
            ->getResult();
    }

}
