<?php

namespace Becek\EstatehunterBundle\Repository\Filters;

/**
 * GroundFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroundFilterRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $limit
     * @return array
     */
    public function findOrderedByDateLastSearchWithLimit($limit)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM BecekEstatehunterBundle:Filters\GroundFilter f ORDER BY f.dateLastSearch')
            ->setMaxResults($limit)
            ->getResult();
    }

    /**
     * @return array
     */
    public function getGroundFilterCount()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(f) FROM BecekEstatehunterBundle:Filters\GroundFilter f')
            ->getResult();
    }

}
