<?php

namespace Becek\EstatehunterBundle\Repository\Filters;

/**
 * HouseFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseFilterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrderedByDateLastSearchWithLimit($limit)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM BecekEstatehunterBundle:Filters\HouseFilter f ORDER BY f.dateLastSearch')
            ->setMaxResults($limit)
            ->getResult();
    }
}
