<?php

namespace Becek\EstatehunterBundle\Repository\Filters;

/**
 * HouseFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseFilterRepository extends \Doctrine\ORM\EntityRepository
{
}
